/*
Print all subsequences of a string
Given a string, we have to find out all subsequences of it. A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.
Examples: 

Input : abc
Output : , a, b, c, ab, bc, ac, abc

Input : aaa
Output : , a, aa, aaa
*/

import java.util.*;
import java.math.*;

public class Main {
    public static void main(String args[]) {
		ArrayList<String> sol=getSubSequence("abc");
		HashSet<String> hset=new HashSet<>();
		hset.addAll(sol);
		System.out.println(hset);
    }
	static ArrayList<String> getSubSequence(String str)
	{
		if(str.length()==0)
		{
			ArrayList<String> base=new ArrayList<>();
			base.add("");
			return base;
		}
		char curChar=str.charAt(0);
		ArrayList<String> myResult=new ArrayList<>();
		ArrayList<String> recResult=getSubSequence(str.substring(1));
		for(int i=0;i<recResult.size();i++)
		{
			myResult.add(recResult.get(i));
			myResult.add(curChar+recResult.get(i));
		}
		return myResult;
	}
}
